[package]
name = "mpd-fresh"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.4"
once_cell = "1.19.0"
percent-encoding = "2.3.1"
reqwest = {version="0.12.4", features=["blocking", "json"]}
serde = {version = "1.0", features=["derive"]}
serde_json = "1.0"
serde_yaml = "0.9"
